okayama_app/urls.py
from django.urls import path
from .import views
app_name='okayama_app'
urlpatterns=[
    path('', views.index, name='index'),
    path('add/',views.add, name='add'),
    path('edit/<int:post_id>/', views.edit, name='edit'),
    path('delete/<int:post_id>/', views.delete, name='delete'),
    path('detail/<int:post_id>/', views.detail, name='detail'),
    #練習用
    path('bootstrap/', views.bootstrap, name='bootstrap'),

]

okayama_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings #追加   
from django.conf.urls.static import static #追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('okayama_app.urls')),
    path('', include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #追加

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views #デフォルト関数の読み込み
 
app_name = 'users'
urlpatterns = [
   path('signup/', views.signup, name='signup'),
   path('users/<int:pk>', views.users, name='users'),
   path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
   path('logout/', auth_views.LogoutView.as_view(), name='logout'),   
]

okayama_app/models.py
from django.db import models
# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User #追加

class Tag(models.Model):
    name=models.CharField('タグ名', max_length=255)
    created_at= models.DateTimeField('作成日', default=timezone.now)
    def __str__(self):
        return self.name

class Post(models.Model):
  title = models.CharField('タイトル', max_length=255)
  text = models.TextField('本文')
  image=models.ImageField('画像', upload_to='images', blank=True)
  created_at = models.DateTimeField('作成日', default=timezone.now)
  tag = models.ForeignKey(Tag, verbose_name='タグ', on_delete=models.PROTECT)
  user = models.ForeignKey(User, on_delete=models.CASCADE)#追加

  def __str__(self):
      return self.title

users/models.py
from django.db import models

# Create your models here.

okayama_app/forms.py
from django import forms
from .models import Post, Tag
from django.forms import ModelForm
 
class PostCreateForm(forms.ModelForm):   
   class Meta:
       model = Post
       fields = ['title', 'text', 'tag']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
 
class UserCreationForm(UserCreationForm):
 
   class Meta:
       model = User
       fields = ('username', 'email', 'password1', 'password2')

okayama_app/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Post, Tag
from .forms import PostCreateForm
from django.db.models import Q #追加

 #省略
 #検証用の関数を追加
def is_valid_q(q):
   return q != '' and q is not None
 #関数内の編集
def index(request):
   posts = Post.objects.all().order_by('-created_at')
   title_or_user = request.GET.get('title_or_user')
   date_min = request.GET.get('date_min')
   date_max = request.GET.get('date_max')
   tag = request.GET.get('tag')

   if is_valid_q(title_or_user):
       posts = posts.filter(Q(title__icontains=title_or_user)
                      | Q(user__username__icontains=title_or_user)
                      ).distinct()

   if is_valid_q(date_min):
       posts = posts.filter(created_at__gte=date_min)

   if is_valid_q(date_max):
       posts = posts.filter(created_at__lt=date_max)

   if is_valid_q(tag) and tag != 'タグを選択...':
       posts = posts.filter(tag__name=tag)
   
   return render(request, 'okayama_app/index.html', 
   {'posts': posts, 'title_or_user': title_or_user , 'date_min': date_min, 'date_max': date_max ,'tag': tag})

def add(request):
   if request.method == "POST":
      form = PostCreateForm(request.POST)
      if form.is_valid():
         post = form.save(commit=False)
         post.user = request.user
         post.save()                    
         return redirect('okayama_app:index')
   else:  
       form = PostCreateForm()
   return render(request, 'okayama_app/add.html', {'form': form})

def edit(request, post_id):
       post = get_object_or_404(Post, id=post_id)
       if request.method == "POST":
           form = PostCreateForm(request.POST, instance=post)
           if form.is_valid():
               form.save()
               return redirect('okayama_app:index')
       else:
               form = PostCreateForm(instance=post)
       return render(request, 'okayama_app/edit.html', {'form': form, 'post':post })

def delete(request, post_id):
   post = get_object_or_404(Post, id=post_id)
   post.delete()
   return redirect('okayama_app:index')

def detail(request, post_id):
   post = get_object_or_404(Post, id=post_id)
   return render(request, 'okayama_app/detail.html', {'post': post})
  
def bootstrap(request):
    return render(request, 'okayama_app/bootstrap.html')

users/views.py
from django.shortcuts import render, redirect, get_object_or_404# 追加
from .forms import UserCreationForm
from django.contrib.auth import authenticate, login
from okayama_app .models import Post, Tag# 追加
from django.contrib.auth.models import User# 追加
 
# Create your views here.
def signup(request):
   user_form = UserCreationForm(request.POST or None)
   if request.method == "POST" and user_form.is_valid():
       user = user_form.save()
       input_username = user_form.cleaned_data['username']
       input_email = user_form.cleaned_data['email']
       input_password = user_form.cleaned_data['password1']
       user = authenticate(username=input_username, email=input_email, password=input_password)
       login(request, user)
       return redirect('okayama_app:index')
   context = {
       "user_form": user_form,
   }
   return render(request, 'users/signup.html', context)

def users(request, pk):
   user = get_object_or_404(User, pk=pk)
   posts = user.post_set.all().order_by('-created_at')
   return render(request, 'users/users.html', {'user': user, 'posts': posts})
  

templates/base.html
<!doctype html>
<html lang="ja">
 <head>
   <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
   <title>プログラミング練習</title>
 </head>
 <body>
   {% include 'header.html' %}
　　<div class="container">
   {% block content %}
   {% endblock %}
 </div>
 {% include 'footer.html' %}
   <!-- Optional JavaScript -->
   <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
 </body>
</html>

templates/footer.html
<div class="footer ">
    <nav class=" text-center d-block navbar fixed-bottom navbar-dark bg-primary text-center">
    <a class="navbar-brand" href="#!">tree dital class</a>
  </nav>
</div>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">ブログサイト</a>
  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="navbar-collapse collapse" id="navbarSupportedContent" style="">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'okayama_app:add' %}">投稿する</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:users' pk=user.pk %}">{{request.user.username}}</a> 
      </li> 
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:logout' %}">ログアウト</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:login' %}">ログイン</a>
      </li>
      {% endif %}
    </ul>
  </div>
 </nav>
 
  

templates/okayama_app/add.html
{% extends 'base.html' %}
{% block content %}
<!-- card -->
<div class="card my-3 text-center">
   <div class="card-header">
       <h1>新規投稿</h1>
   </div>
   <div class="card-body">
     <p class="card-text">
         <form action="/add/" method="POST"><input type="hidden" name="csrfmiddlewaretoken" value="JRtCnOU0AJALFMBmhZiY8Cg3eD8cKKaHqMWE2Tv0aZ2XYYjorvF3caBy9LbGp7Ju">
{% csrf_token %}
           <div class="form-group">
               <input name="title" maxlength="255" type="text" class="form-control" id="id_title" placeholder="タイトル">
           </div>
           <div class="form-group">
               <textarea name="text" cols="40" rows="10" class="form-control" placeholder="本文" required="" id="id_text"></textarea>
           </div>
          
           <select class="form-control" name="category" required="" id="id_category">
               <option value="1">犬</option>
               <option value="2">猫</option>
               <option value="3">プログラム</option>
           </select>
 
      
       </p>   
    <button class="btn btn-primary" type="submit">投稿する</button>
   </form></p>
   </div>
 </div>
 
</div>
{% endblock %}

templates/okayama_app/bootstrap.html
{% extends 'base.html' %}
{% block content %}

<h1>boostrap</h1>

{% endblock %}

templates/okayama_app/detail.html
{% extends 'base.html' %}
{% block content %}
<h2>タイトル：{{ post.title }}</h2>
<p>内容：{{ post.text }}</p>
<p>カテゴリー：{{ post.category }}</p>
{% endblock %}

templates/okayama_app/edit.html
{% extends 'base.html' %}
{% block content %}
 <form method="POST">{% csrf_token %}
   <h1>編集ページ</h1>
   {{ form.as_p }}
   <button class="btn btn-primary" type="submit">編集する</button>
</form>
{% endblock %}

templates/okayama_app/filter.html
<h4 class="card-title text-secondary text-center">絞り込み検索</h4>
<form method="GET" action="{% url 'okayama_app:index' %}">
 <div class="form-row">
     <div class="form-group col-12">
         <div class="input-group">
             <input class="form-control py-2 border-right-0 border" type="search" name="title_or_user" placeholder="タイトル or ユーザー名..." value="{{request.GET.title_or_user}}" />
             <span class="input-group-append">
                 <div class="input-group-text bg-transparent">
                     <i class="fa fa-search"></i>
                 </div>
             </span>
         </div>
     </div>        
 </div>
 <div class="form-row">
   <div class="form-group col-md-12 col-lg-6">
     <label for="publishDateMin">開始日〜</label>
     <input type="date" class="form-control" id="publishDateMin" name="date_min" value="{{request.GET.date_min}}">
   </div>
   <div class="form-group col-md-12 col-lg-6">
     <label for="publishDateMax">〜終了日</label>
     <input type="date" class="form-control" id="publishDateMax" name="date_max" value="{{request.GET.date_max}}">
   </div>
   <div class="form-group col-md-12">
     <label for="category">タグ</label>
     <select id="tag" class="form-control" name="tag">
       <option selected>タグを選択...</option>
       {% for tag in tags %}
       <option value="{{ tag }}">{{ tag }}</option>
       {% endfor %}
     </select>
   </div>
 </div>
 <button style="width: 100%;" type="submit" class="btn btn-primary">絞り込み</button>
</form>

templates/okayama_app/index.html
{% extends 'base.html' %}
{% block content %}
 
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
 <div class="carousel-inner" role="listbox">
   <div class="carousel-item active">
     <img class="d-block w-100" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22900%22%20height%3D%22400%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20900%20400%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16f97e0e6a9%20text%20%7B%20fill%3A%23FFFFFF%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A45pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16f97e0e6a9%22%3E%3Crect%20width%3D%22900%22%20height%3D%22400%22%20fill%3D%22%233a5a97%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22333.203125%22%20y%3D%22220.1%22%3E900x400%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-src="holder.js/900x400?theme=social" alt="900x400" data-holder-rendered="true" style="width: 900px; height: 400px;">
   </div>
   <div class="carousel-item">
     <img class="d-block w-100" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22900%22%20height%3D%22400%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20900%20400%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16f97e0e67e%20text%20%7B%20fill%3A%23C2F200%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A45pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16f97e0e67e%22%3E%3Crect%20width%3D%22900%22%20height%3D%22400%22%20fill%3D%22%23434A52%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22333.203125%22%20y%3D%22220.1%22%3E900x400%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-src="holder.js/900x400?theme=industrial" alt="900x400" data-holder-rendered="true" style="width: 900px; height: 400px;">
   </div>
 </div>
 <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
   <span class="carousel-control-prev-icon" aria-hidden="true"></span>
   <span class="sr-only">Previous</span>
 </a>
 <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
   <span class="carousel-control-next-icon" aria-hidden="true"></span>
   <span class="sr-only">Next</span>
 </a>
</div>
  
<h1 class="text-center my-4">Blog</h1>

<button data-toggle="modal" data-target=".bd-example-modal-lg" style="margin: 0 auto;" type="button" class="btn btn-primary d-block my-3 px-5"><i class="fa fa-search">検索</i></button>
 <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
   <div class="modal-dialog modal-xl">
     <div class="modal-content">
       <div class="card text-align-center">
         <div class="card-body">
           {% include 'okayama_app/filter.html' %}
         </div>
       </div>
     </div>
   </div>
 </div>
{% if title_or_user or date_min or date_max or tag %}
<p class="mb-0 text-center font-weight-bold h3">検索結果：{{posts.count}}件</p>
<table class="table table-bordered">
 <thead class="thead-light">
   <tr>
     <th>タイトル or ユーザー名</th>
     <th>開始日〜終了日</th>
     <th>タグを選択</th>
   </tr>
 </thead>
 <tbody>
   <tr>
     <td>{{request.GET.title_or_user}}</td>
     <td>{{request.GET.date_min}}〜{{request.GET.date_max}}</td>
     <td>{{request.GET.tag}}</td>
   </tr>
 </tbody>
</table>
{% endif %}


<div class="row justify-content-around">
{% for post in posts %}
<div class="card my-3" style="width: 350px;">
{% if post.image %}
 <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
 {% else %}
 <p style="height: 183px;">no image</p>
 {% endif %}
 <div class="card-body">
   <h4 class="card-title"><a href="{% url 'okayama_app:detail' post_id=post.id %}"><h4>タイトル：{{ post.title }}</h4></a>
   <p class="card-text">
     内容：{{ post.text }}
   </p>
   <p class="card-text">
     カテゴリー：{{ post.tag }}
   </p>
   <p>{{post.created_at}}</p>
 </div>
</div>
{% endfor %}
</div>
{% endblock %}

templates/users/login.html
<h2>Login</h2>
<form method="post">
 {% csrf_token %}
 {{ form.as_p }}
 <button type="submit">Login</button>
</form>

templates/users/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
 <div class="card-body">
   <h4 class="card-title">Sign up</h4>
   <form class="form-signin" method="post">{% csrf_token %}
   <p class="card-text">
   <label for="inputUsername" class="sr-only">アーティスト名</label>
   <input type="text" id="inputUsername" name="username" class="form-control mb-3" placeholder="ユーザー名" required autofocus>
   <label for="id_email" class="sr-only">メールアドレス</label>
   <input type="email" name="email" maxlength="254" class="form-control mb-3" placeholder="メールアドレス" required id="id_email">
   <label for="id_password1" class="sr-only">パスワード</label>
   <input type="password" id="inputPassword" name="password1" class="form-control mb-3" placeholder="パスワード" required>
   <label for="id_password2" class="sr-only">パスワード(確認用)</label>
   <input type="password" id="inputPassword" name="password2" class="form-control mb-3" placeholder="パスワード(確認)" required>
   <button type="submit" class="btn btn-primary">Sign up</button>
       </p>
       </form>
   <p>既にアカウントをお持ちですか?? <a href="{% url 'users:login' %}">Login</a></p>
 </div>
</div>
{% endblock %}

templates/users/users.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center my-4">{{user.username}}のページ</h1>
<div class="row justify-content-around">
{% for post in posts %}
<div class="card my-3" style="width: 350px;">
 <img class="card-img-top" src="/images/pathToYourImage.png" alt="Card image cap">
 <div class="card-body">
   <h4 class="card-title">タイトル：{{ post.title }}</h4>
   <p class="card-text">
     内容：{{ post.text }}</p>
    
   <p class="card-text">
     <p>カテゴリー：{{ post.category }}
   </p>
   {% if request.user == post.user %}
 <a href="{% url 'okayama_app:edit' post_id=post.id %}" class="btn btn-primary">編集</a>
 <a href="{% url 'okayama_app:delete' post_id=post.id %}" class="btn btn-danger">削除</a>
 {% endif %}
 </div>
</div>
 
{% endfor %}
</div>
{% endblock %}